### ISSUE TITLE
<div> and <p> are inconsistently applied

### ISSUE THREAD

**Issue by duncdrum** [hcts-hra/ecpo#150]
e.g.: do we really need 3 x `<p> [here?](https://github.com/hcts-hra/ecpo/blob/03ef9eb6a743db01b6c3ffecdb08c4676605850b/jingbao/1920/04/jb_0129_1920-04-03_0002+0003.xml#L5) what is that supposed to encode
```xml
<div type="margin" mode="horizontal-tb" dir="rtl">
            <p>
                第二版　民國九年四月三日<lb/>
            </p>
            <p>
                晶報<lb/>
            </p>
            <p>
                庚申年二月十五日　星期六<lb/>
            </p>
        </div>
```

we need to clean this up

**Comment by xiejia1995** [comment]
<img width="362" alt="2022-09-14 18_09_52-ISSUE _ 12 9 (1920-04-03) 晶報 - JING BAO - _THE CRYSTAL_" src="https://user-images.githubusercontent.com/76219575/190206604-0577d269-fe63-4837-b93b-29683a28183a.png">
this was because the title "晶報" is written in a handwritten font.

**Comment by duncdrum** [comment]
Interesting, but we re not encoding font choices, so without further attributes it’s a meaningless distinction. 

It looks more like bold, of the same type as the surrounding type face, to me. Looking at the screenshot in here

**Comment by duncdrum** [comment]
also of note this is a single line of text, our encoding turns it into three paragraps with 1 line-break each, there are no line breaks: this should be
```xml
<p>第二版　民國九年四月三日　晶報　庚申年二月十五日　星期六</lb></p>
```

**Comment by duncdrum** [comment]
superseded by #152
