### ISSUE TITLE
typing "double-space" comma

### ISSUE THREAD

**Issue by MatthiasArnold** [hcts-hra/ecpo#68]
found in jb_3797_1939-04-23_005to008 page 8, upper part, middle, article 上海究竟有幾個電影公司
in column 3, line 2 there is a comma that fills teh space of TWO characters. therefore the line only consists of 7 (instead of 8) chars.
how should this be typed?
just as a single comma: 祥掌管，攝影場
or with additional (fullwidth) space?

image: ![2021-07-29_15-19-05](https://user-images.githubusercontent.com/3436613/127501030-b5cd39d2-ddc2-499f-9d01-8e07a9f14ef2.png)

**Comment by MatthiasArnold** [comment]
notes from Louise Yip <ysmlouis@msn.com>, 2021-07-30
fold 1939.04.23_02+03 line 345
fold 1939.04.23_05+08 Line 181, Line 182, Line 540
fold 1939.04.23_06+07 Line 958
fold 1939.04.25_01+04 line 69, Line 202-205, Line 278, Line 295, Line 579-620
fold 1939.04.25_02+03 line 889

**Comment by duncdrum** [comment]
this doesn't look to me like typographic spaces, but like justification on the paragraph level. For encoding i would not add spaces here so : `祥掌管，攝影場` is essentially correct.
