### ISSUE TITLE
whitespaces

### ISSUE THREAD

**Issue by MatthiasArnold** [hcts-hra/ecpo#70]
found in jb_3797_1939-04-23_005to008 page 8, upper part, right, column 影城
there are repeated "x" charaters between different text sections. how to record them?

as lower case "x", i.e. ´´´xxx´´´?
as lower case "x" with spaces, i.e. ´´´x x x´´´?
as lower case "x" with full width spaces, i.e. ´´´x　x　x´´´?
as fullwidth lower case "x" with full width spaces, i.e. ´´´ｘ　ｘ　ｘ´´´?
as fullwidth lower case "x" with ｔｗｏ　full width spaces, i.e. ´´´ｘ　　ｘ　　ｘ´´´?

similar:
at the end there is a "signature" added "（能）", separated by multiple white spaces.
do these need to be counted? or is ｏｎｅ fullwidth space enough, or can the whitespace be ignored?

image: 
![2021-07-29_15-20-04_1](https://user-images.githubusercontent.com/3436613/127503235-cfac0ece-02dc-478a-98d4-f44d510a4b19.png)

**Comment by xiejia1995** [comment]
a similar question for the star marks. shall we mark them as ★(U+2605)? do we also record their rotations?
![stars in 04-30 p8](https://user-images.githubusercontent.com/76219575/131717133-9dc6203c-703b-4da1-b6b2-7f7833b82edc.jpg)

**Comment by MatthiasArnold** [comment]
answer:
a) fullwidth lower case "x" with full width spaces, i.e. ´´´ｘ　ｘ　ｘ´´´?
b) no rotation of the stars needed. just write "★　★"
